springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

cloud:
  aws:
    region:
      static: us-east-1
    credentials:
      access-key: "dummy-access-key"
      secret-key: "dummy-secret-key"
    sqs:
      endpoint: "http://localhost:4566"

server:
  port: 8089

spring:
  redis:
    host: localhost
    port: 6379
    password: ""  # (Optional)
    database: 0
