version: "3.8"
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack_main
    ports:
      - "4566:4566"  # Gateway
      - "4571:4571"  # DynamoDB
    environment:
      - SERVICES=sqs,dynamodb
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - DEBUG=1
    volumes:
      - ./localstack-data:/var/lib/localstack

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - redis-net
    volumes:
      - redis-data:/data

networks:
  redis-net:
    driver: bridge

volumes:
  redis-data:
